CREATE DATABASE databaugs;

CREATE USER app_databaugs
WITH LOGIN
PASSWORD 'AppBD2_2026';

CREATE ROLE replicador
WITH LOGIN REPLICATION
PASSWORD 'ReplicacionBD2_2026';

GRANT ALL PRIVILEGES ON DATABASE databaugs TO app_databaugs;
