CREATE DATABASE databaugs;

CREATE USER bd2_admin WITH PASSWORD 'CAMBIAR_PASSWORD';

CREATE ROLE replicador
WITH LOGIN REPLICATION
PASSWORD 'CAMBIAR_PASSWORD_REPLICACION';

GRANT ALL PRIVILEGES ON DATABASE databaugs TO bd2_admin;