# Acceso local
local   all             all                                     scram-sha-256
host    all             all             127.0.0.1/32            scram-sha-256
host    all             all             ::1/128                 scram-sha-256

# Acceso remoto Nodo 2
host    databaugs       bd2_admin       IP_KENNY/32              scram-sha-256
host    replication     replicador      IP_KENNY/32              scram-sha-256

# Acceso remoto Nodo 3
host    databaugs       bd2_admin       IP_MIGUEL/32             scram-sha-256
host    replication     replicador      IP_MIGUEL/32             scram-sha-256