# Acceso local
local   all             all                                     scram-sha-256
host    all             all             127.0.0.1/32            scram-sha-256
host    all             all             ::1/128                 scram-sha-256

# Nodo 2 - Kenny
host    databaugs       app_databaugs   100.100.231.68/32       scram-sha-256
host    databaugs       replicador      100.100.231.68/32       scram-sha-256

# Nodo 3 - Miguel
host    databaugs       app_databaugs   100.89.187.125/32       scram-sha-256
host    databaugs       replicador      100.89.187.125/32       scram-sha-256
